apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy-ui-backend
  namespace: trivy-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy-ui-backend
  template:
    metadata:
      labels:
        app: trivy-ui-backend
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: trivy-ui-backend
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 1000
            runAsGroup: 1000
          image: camelel/trivy-ui-backend:latest
          imagePullPolicy: Always
          env:
            - name: DB_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: postgres
                  key: DB_BACKEND
            - name: POSTGRES_SERVER
              valueFrom:
                configMapKeyRef:
                  name: postgres
                  key: DB_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres
                  key: DB_PORT
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres
                  key: DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: DB_APP_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: DB_APP_PASSWORD
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
          volumeMounts:
            - name: reports-volume
              mountPath: /app/backend/app/storage/reports
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      volumes:
        - name: reports-volume
          persistentVolumeClaim:
            claimName: reports-pvc
