apiVersion: v1
kind: PersistentVolume
metadata:
  name: reports-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /Users/itaig/src/trivy-ui/backend/app/storage/reports
