version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: trivy-ui-backend
    working_dir: /app/backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./backend/app/storage/reports:/app/storage/reports
    environment:
      - UVICORN_RELOAD=true
      - TZ=Asia/Jerusalem
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - trivy-ui-network

  frontend:
    container_name: trivy-ui-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev -- --host
    depends_on:
      - backend
    networks:
      - trivy-ui-network

networks:
  trivy-ui-network:
    driver: bridge
