version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: trivy-ui-backend
    working_dir: /app/backend # <-- point at your code root
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend # <-- now /app/backend/app/storage/reports will exist
    environment:
      - UVICORN_RELOAD=true
      - TZ=Asia/Jerusalem
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - trivy-ui-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: trivy-ui-frontend
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - trivy-ui-network

networks:
  trivy-ui-network:
    driver: bridge
