version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: trivy-ui-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./backend/reports:/app/reports
    working_dir: /app/backend
    environment:
      - UVICORN_RELOAD=true
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - trivy-ui-network

  frontend:
    build:
      context: ./frontend
    container_name: trivy-ui-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - trivy-ui-network

networks:
  trivy-ui-network:
    driver: bridge
