version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: trivy-ui-backend
    restart: unless-stopped
    working_dir: /app/backend
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    volumes:
      - ./backend/app/storage/reports:/app/storage/reports
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 2
    networks:
      - trivy-ui-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: trivy-ui-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - trivy-ui-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  trivy-ui-network:
    driver: bridge
