version: 1

formatters:
  rich:
    (): rich.logging.RichHandler
    rich_tracebacks: true
    tracebacks_show_locals: true
    markup: true
    show_time: true
    show_level: true
    show_path: false

  default:
    format: "%(levelname)-8s | %(asctime)s | %(name)s | %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    formatter: rich
    stream: ext://sys.stdout

  access_console:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

loggers:
  uvicorn:
    handlers: [console]
    level: INFO
    propagate: False

  uvicorn.error:
    handlers: [console]
    level: INFO
    propagate: False

  uvicorn.access:
    handlers: [access_console]
    level: INFO
    propagate: False

  app:
    handlers: [console]
    level: DEBUG
    propagate: False

root:
  handlers: [console]
  level: INFO
