apiVersion: apps/v1
kind: Deployment
metadata:
  name: trivy-ui-frontend
  namespace: trivy-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trivy-ui-frontend
  template:
    metadata:
      labels:
        app: trivy-ui-frontend
    spec:
      containers:
        - name: trivy-ui-frontend
          image: host.docker.internal:5001/trivy-ui-frontend:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres
                  key: DB_NAME
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres
                  key: DB_HOST
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres
                  key: DB_ROOT_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: DB_ROOT_PASSWORD
            - name: DB_APP_USER
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: DB_APP_USER
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgres
                  key: DB_PORT
            - name: DB_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: DB_APP_PASSWORD
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 80
