apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  namespace: trivy-ui
data:
  DB_BACKEND: filesystem
  DB_HOST: postgres.trivy-ui.svc.cluster.local
  DB_NAME: trivydb
  DB_ROOT_USER: postgres
  DB_PORT: "5432"
